require('dotenv').config();
const path = require('path');
const express = require('express');
const cookieParser = require('cookie-parser');
const methodOverride = require('method-override');
const shopRoutes = require('./routes/shop.routes');
const authRoutes = require('./routes/auth.routes');
const cartRoutes = require('./routes/cart.routes');
const orderRoutes = require('./routes/order.routes');
const adminRoutes = require('./routes/admin.routes');
const profileRoutes = require('./routes/profile.routes');
const authMiddleware = require('./middlewares/auth.middleware');
const { notFound, errorHandler } = require('./middlewares/error.middleware');
const app = express();
const PORT = process.env.PORT || 3000;
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
app.use(express.static(path.join(__dirname, 'public')));
app.use('/uploads', express.static(path.join(__dirname, 'public', 'uploads')));
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(cookieParser());
app.use(methodOverride('_method'));
app.use(authMiddleware.attachUser);
app.use((req,res,next)=>{res.locals.currentUser=req.user||null;res.locals.query=req.query;next();});
app.use('/', shopRoutes);
app.use('/auth', authRoutes);
app.use('/cart', cartRoutes);
app.use('/orders', orderRoutes);
app.use('/admin', adminRoutes);
app.use('/profile', profileRoutes);
app.use(notFound);
app.use(errorHandler);
app.listen(PORT, ()=> console.log(`Сервер запущен: http://localhost:${PORT}`));
